### ISSUE TITLE
Where is pgq.event_failed?

### ISSUE THREAD

**Issue by andrew-plunk** [pgq/pgq#1]
After reading the documentation I would like to use pgq.event_failed, however this function does not appear to exist other than in the documentation:

```
>ag event_failed
structure/func_public.sql
21:--         pgq.event_failed(batch_id int8, event_id int8, reason text)

```

What happened to this function?

**Comment by markokr** [comment]
It's obsolete.  Without any infra to review and delete failed events this api was just black hole for problem hiding.  So it was removed.
