### ISSUE TITLE
test pgq_perms ... FAILED

### ISSUE THREAD

**Issue by joelonsql** [pgq/pgq#10]
Hi,

Thanks for making this extension.

I've tested it on Ubuntu 20.04.2 LTS running Ubuntu 13.2-1.pgdg20.04+1.

2 tests are failing:

    $ make installcheck
    /usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --dbname=regression --dbname=regression  pgq_init_ext pgq_core pgq_core_disabled pgq_core_tx_limit pgq_session_role pgq_perms trigger_base trigger_sess_role trigger_types trigger_trunc trigger_ignore trigger_pkey trigger_deny trigger_when trigger_extra_args trigger_extra_cols clean_ext pgq_init_ext switch_plonly pgq_core pgq_core_disabled pgq_session_role pgq_perms trigger_base trigger_sess_role trigger_types trigger_trunc trigger_ignore trigger_pkey trigger_deny trigger_when trigger_extra_args trigger_extra_cols
    (using postmaster on Unix socket, default port)
    ============== dropping database "regression"         ==============
    DROP DATABASE
    ============== creating database "regression"         ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== running regression test queries        ==============
    test pgq_init_ext                 ... ok          173 ms
    test pgq_core                     ... ok          128 ms
    test pgq_core_disabled            ... ok           50 ms
    test pgq_core_tx_limit            ... ok           49 ms
    test pgq_session_role             ... ok           74 ms
    test pgq_perms                    ... FAILED (test process exited with exit code 2)       36 ms
    test trigger_base                 ... ok           61 ms
    test trigger_sess_role            ... ok          121 ms
    test trigger_types                ... ok          114 ms
    test trigger_trunc                ... ok           73 ms
    test trigger_ignore               ... ok           27 ms
    test trigger_pkey                 ... ok           26 ms
    test trigger_deny                 ... ok           39 ms
    test trigger_when                 ... ok           26 ms
    test trigger_extra_args           ... ok           29 ms
    test trigger_extra_cols           ... ok           31 ms
    test clean_ext                    ... ok           21 ms
    test pgq_init_ext                 ... ok          175 ms
    test switch_plonly                ... ok           24 ms
    test pgq_core                     ... ok          127 ms
    test pgq_core_disabled            ... ok           48 ms
    test pgq_session_role             ... ok           76 ms
    test pgq_perms                    ... FAILED (test process exited with exit code 2)       39 ms
    test trigger_base                 ... ok           91 ms
    test trigger_sess_role            ... ok          124 ms
    test trigger_types                ... ok          394 ms
    test trigger_trunc                ... ok           82 ms
    test trigger_ignore               ... ok           51 ms
    test trigger_pkey                 ... ok           38 ms
    test trigger_deny                 ... ok           46 ms
    test trigger_when                 ... ok           38 ms
    test trigger_extra_args           ... ok           51 ms
    test trigger_extra_cols           ... ok           56 ms

    =======================
    2 of 33 tests failed.
    =======================

    $ cat regression.diffs
    diff -U3 /home/joel/postgresql-extensions/pgq/expected/pgq_perms.out /home/joel/postgresql-extensions/pgq/results/pgq_perms.out
    --- /home/joel/postgresql-extensions/pgq/expected/pgq_perms.out	2021-04-26 05:53:48.276867158 +0000
    +++ /home/joel/postgresql-extensions/pgq/results/pgq_perms.out	2021-04-26 05:55:28.818139878 +0000
    @@ -6,44 +6,4 @@
    create role pgq_test_producer with login in role pgq_writer;
    create role pgq_test_admin with login in role pgq_admin;
    \c - pgq_test_admin
    -select * from pgq.create_queue('pqueue'); -- ok
    - create_queue
    ---------------
    -            1
    -(1 row)
    -
    -\c - pgq_test_producer
    -select * from pgq.create_queue('pqueue'); -- fail
    -ERROR:  permission denied for function create_queue
    -select * from pgq.insert_event('pqueue', 'test', 'data'); -- ok
    - insert_event
    ---------------
    -            1
    -(1 row)
    -
    -select * from pgq.register_consumer('pqueue', 'prod'); -- fail
    -ERROR:  permission denied for function register_consumer
    -\c - pgq_test_consumer
    -select * from pgq.create_queue('pqueue'); -- fail
    -ERROR:  permission denied for function create_queue
    -select * from pgq.insert_event('pqueue', 'test', 'data'); -- fail
    -ERROR:  permission denied for function insert_event
    -select * from pgq.register_consumer('pqueue', 'cons'); -- ok
    - register_consumer
    --------------------
    -                 1
    -(1 row)
    -
    -select * from pgq.next_batch('pqueue', 'cons'); -- ok
    - next_batch
    -------------
    -
    -(1 row)
    -
    -\c - pgq_test_admin
    -select * from pgq.drop_queue('pqueue', true);
    - drop_queue
    -------------
    -          1
    -(1 row)
    -
    +\connect: FATAL:  Peer authentication failed for user "pgq_test_admin"
    diff -U3 /home/joel/postgresql-extensions/pgq/expected/pgq_perms.out /home/joel/postgresql-extensions/pgq/results/pgq_perms.out
    --- /home/joel/postgresql-extensions/pgq/expected/pgq_perms.out	2021-04-26 05:53:48.276867158 +0000
    +++ /home/joel/postgresql-extensions/pgq/results/pgq_perms.out	2021-04-26 05:55:29.914151571 +0000
    @@ -6,44 +6,4 @@
    create role pgq_test_producer with login in role pgq_writer;
    create role pgq_test_admin with login in role pgq_admin;
    \c - pgq_test_admin
    -select * from pgq.create_queue('pqueue'); -- ok
    - create_queue
    ---------------
    -            1
    -(1 row)
    -
    -\c - pgq_test_producer
    -select * from pgq.create_queue('pqueue'); -- fail
    -ERROR:  permission denied for function create_queue
    -select * from pgq.insert_event('pqueue', 'test', 'data'); -- ok
    - insert_event
    ---------------
    -            1
    -(1 row)
    -
    -select * from pgq.register_consumer('pqueue', 'prod'); -- fail
    -ERROR:  permission denied for function register_consumer
    -\c - pgq_test_consumer
    -select * from pgq.create_queue('pqueue'); -- fail
    -ERROR:  permission denied for function create_queue
    -select * from pgq.insert_event('pqueue', 'test', 'data'); -- fail
    -ERROR:  permission denied for function insert_event
    -select * from pgq.register_consumer('pqueue', 'cons'); -- ok
    - register_consumer
    --------------------
    -                 1
    -(1 row)
    -
    -select * from pgq.next_batch('pqueue', 'cons'); -- ok
    - next_batch
    -------------
    -
    -(1 row)
    -
    -\c - pgq_test_admin
    -select * from pgq.drop_queue('pqueue', true);
    - drop_queue
    -------------
    -          1
    -(1 row)
    -
    +\connect: FATAL:  Peer authentication failed for user "pgq_test_admin"

**Comment by markokr** [comment]
It looks like local setup does not allow connections with 'pgq_test_admin' user, that cannot be fixed from tests side.

Either allow it (eg. set up .pgpass for that user) or run tests against more relaxed postgres cluster.
