### ISSUE TITLE
Will there be support for Postgres 14. 

### ISSUE THREAD

**Issue by vald7777** [pgq/pgq#14]
Hello. 
We are planning upgrades to PG14 and currently pgq is not working with PG14. Are you planning to add support for PG14? 
As I see only PG13 is supported at the moment.

**Comment by markokr** [comment]
What is the problem with pg14?

From my testing, it seems to work with both pg14 and pg15.

**Comment by markokr** [comment]
> `pgq_lowlevel.so: undefined symbol: elog_finish`

it does seem the .so is built with some other version of postgres.  could you rebuild it with pg14?

If the problem persist, please send build log.
