### ISSUE TITLE
fast tick catch up

### ISSUE THREAD

**Issue by DeoLeung** [pgq/pgq#17]
Hi,

just new to pgq.
I'm using pg13 with pgq3.5 and ticking it with pgqd3.3(the debian package is not ready)

I'm facing a problem
```sql
-- get 8
SELECT pgq.next_batch_info('deo', 'worker1');
-- return nothing
SELECT pgq.get_batch_events(8);
-- if i finish it, the tick simply turn to 9, without data(after fiddling, found that it should be the cause of invoking `next_batch*`)
SELECT pgq.finish_batch(8);

-- i check the event table
SELECT pgq.current_event_table('deo');
-- events are still there, not maint
SELECT * FROM pgq.event_2_1;

-- after finish_event, I simply increase it by 1
-- this raise error
SELECT pgq.get_batch_events(9);
-- but if I call, it immediately increase 1
SELECT pgq.next_batch_info('deo', 'worker1');
-- but still empty
SELECT pgq.get_batch_events(9);
```

should I use pgqd3.5 only? or is there any method I should take to reset the queues/workers to make it work normal?

**Comment by DeoLeung** [comment]
Having playing around for a while, finally got to understand the `tick` concept.

A tick prepares a batch, and each time we consume a tick.

Then my questions come to:
1. if my `pgqd` keep tick in 1s but my producer generate just a few every hour, is it back to have tons of empty ticks? how to avoid them?
2. if my consumer stops for a while, how can I do fast catch up, except looping all the generated ticks?
3. will the empty ticks stop or how to control it? I started a `pgqd` with 1s interval a few days ago and today I see only ~10k in `pgq.tick` table, there shall be some setting for that?

**Comment by markokr** [comment]
1. If there are no events, ticker uses `queue_ticker_idle_period` (1m) to generate batches. you can tune the bigger if you have slow queue.
2. Looping is usually the correct approach, especially if you have queue configured correctly, there are not that many batches, and processing them is fast.  (Alternative would be to use `i_min_interval` arg for `next_batch_custom`, but its bit more complicated)
3. Empty ticks are normal, you can use `queue_ticker_idle_period` to configure the frequency of them.
