### ISSUE TITLE
consumer function is not getting triggered automatically

### ISSUE THREAD

**Issue by althaf004** [pgq/pgq#18]
Hi team,

We where trying to run the pgq for our project.  I have my snippets below. 

-- _**enable extension**_
`create extension pgq;`

-- **_create new queue_**
`select pgq.create_queue('event_email');`

-- **_insert an event_**
`select pgq.insert_event('event_email', 'send_email', '{"recipient" : "alth@gmail.com", "subject" : "Test mail", "body" : "Mail send successfully"}');`

-- **_consumer function_**
```
CREATE OR REPLACE FUNCTION pgq_queue_consumer(queue_data text, consumer text)
 RETURNS SETOF text
 LANGUAGE plpgsql
AS $function$
DECLARE
  event_row RECORD;
  id BIGINT;
  event_data TEXT;
  email_data JSONB; query_out text; Mail_out text;
  recipient TEXT;
  subject TEXT;
  body TEXT;
begin
  SET search_path = pgq;
  -- Get the batch ID
  SELECT pgq.next_batch(queue_data, consumer) INTO id;

  -- Process each event in the batch
  FOR event_row IN SELECT * FROM pgq.get_batch_events(id) LOOP
    -- Extract email data from event
    event_data := event_row.ev_data;
    email_data := jsonb(event_data);
    recipient := email_data->>'recipient'::text;
    subject := email_data->>'subject'::text;
    body := email_data->>'body'::text;

    -- Send email using some email sending library
	query_out := ('select public.send_email('....')')

	execute query_out into Mail_out;   
  
    -- Return event ID
    RETURN NEXT event_row.ev_id;
  END LOOP;

  -- Mark the batch as processed
  PERFORM pgq.finish_batch(id);

  -- Return 'Success'
  RETURN NEXT 'Success';
END;
$function$
;
```
-- **_registration of consumer._**
`select pgq.register_consumer('event_email','pgq_queue_consumer');`

ticker - pgqd is running at the back end which is inserting entries to tick table with a timegap of 1 min.

Is there any steps im missing, which the consumer function will be called and mail will be send out.

thanks

**Comment by markokr** [comment]
You need to call the function yourself, from some db client.

The pgq.next_batch() will return NULL if there is no batch available, then sleep a bit and try again.
If it did return batch successfully, then do not sleep, try for next batch immediately until you gen NULL.
